# For manual local tests
services:
  debian-13:
    image: debian:13
    container_name: security-scripts-testing-debian-13
    stdin_open: true
    tty: true
    volumes:
      - ../../../.:/Security-Scripts
  ubuntu-24.04:
    image: ubuntu:24.04
    container_name: security-scripts-testing-ubuntu-24.04
    stdin_open: true
    tty: true
    volumes:
      - ../../../.:/Security-Scripts
  oraclelinux-10:
    image: oraclelinux:10
    container_name: security-scripts-testing-oraclelinux-10
    stdin_open: true
    tty: true
    volumes:
      - ../../../.:/Security-Scripts
  oraclelinux-9:
    image: oraclelinux:9
    container_name: security-scripts-testing-oraclelinux-9
    stdin_open: true
    tty: true
    volumes:
      - ../../../.:/Security-Scripts
  fedora-43:
    image: fedora:43
    container_name: security-scripts-testing-fedora-43
    stdin_open: true
    tty: true
    volumes:
      - ../../../.:/Security-Scripts
  opensuse-leap-15:
    image: opensuse/leap:15
    container_name: security-scripts-testing-opensuse-15
    stdin_open: true
    tty: true
    volumes:
      - ../../../.:/Security-Scripts