name: Package and Release harden-comp

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Runs when you push version tags
      - '[0-9]+.[0-9]+.[0-9]+-*'  # 1.0.0-rc1, 1.0.0-beta1, etc

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tar.xz archive
        run: |
          mkdir -p dist
          VERSION="${GITHUB_REF_NAME}"  # tag name
          tar -cJf "dist/harden-comp-${VERSION}.tar.xz" -C Linux harden-comp

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Security-Scripts ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          files: dist/harden-comp-${{ github.ref_name }}.tar.xz
          body: |
            Automated release for `${{ github.ref_name }}`.
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_PAT }}
