name: Package and Release harden-comp

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tar.xz archive
        run: |
          mkdir -p dist
          tar -cJf "dist/harden-comp.tar.xz" -C Linux harden-comp
          chmod +x dist/harden-comp.tar.xz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Security Scripts ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          files: dist/harden-comp.tar.xz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_PAT }}
